config/routes.rb
Grooopme::Application.routes.draw do
  resources :time_blocks, :days, :schedules, :groups, :memberships

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "signup_wizard", :to => "registrations#signup_wizard"
  end
  
  resources :users, :only => [:index, :show]

  root :to => "pages#home"
  match "/signed_up" => "pages#signed_up", :as => "signed_up"
  match "/waiting_for_confirmation" => "pages#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/download" => "users#download", :as => "download"
  match "/stats" => "pages#stats", :as => "stats"
  match "/roster" => "pages#roster", :as => "roster"
  
  #Comments
  #=======================#
  match "/add_comment" => "comments#create", :as => "add_comment"
  match "/update_comment" => "comments#update", :as => "update_comment"
  match "/destroy_comment" => "comments#destroy", :as => "destroy_comment"
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :user_id, :group_id, :compatibility_score
  belongs_to :user
  belongs_to :group
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @memberships = Membership.all
  end

  def show
    @membership = Membership.find(params[:id])
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(params[:membership])
    if @membership.save
      redirect_to @membership, :notice => "Successfully created membership."
    else
      render :action => 'new'
    end
  end

  def edit
    @membership = Membership.find(params[:id])
  end

  def update
    @membership = Membership.find(params[:id])
    if @membership.update_attributes(params[:membership])
      redirect_to @membership, :notice  => "Successfully updated membership."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy
    redirect_to memberships_url, :notice => "Successfully destroyed membership."
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for @membership do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/memberships/edit.html.erb
<% title "Edit Membership" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @membership %> |
  <%= link_to "View All", memberships_path %>
</p>

app/views/memberships/index.html.erb
<% title "Memberships" %>

<table>
  <tr>
    <th>User</th>
    <th>Group</th>
  </tr>
  <% for membership in @memberships %>
    <tr>
      <td><%= membership.user_id %></td>
      <td><%= membership.group_id %></td>
      <td><%= link_to "Show", membership %></td>
      <td><%= link_to "Edit", edit_membership_path(membership) %></td>
      <td><%= link_to "Destroy", membership, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Membership", new_membership_path %></p>

app/views/memberships/new.html.erb
<% title "New Membership" %>

<%= render 'form' %>

<p><%= link_to "Back to List", memberships_path %></p>

app/views/memberships/show.html.erb
<% title "Membership" %>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>
<p>
  <strong>Group:</strong>
  <%= @membership.group_id %>
</p>

<p>
  <%= link_to "Edit", edit_membership_path(@membership) %> |
  <%= link_to "Destroy", @membership, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", memberships_path %>
</p>