config/routes.rb
Grooopme::Application.routes.draw do
  resources :time_blocks, :days, :schedules, :groups, :memberships

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "signup_wizard", :to => "registrations#signup_wizard"
  end
  
  resources :users, :only => [:index, :show]

  root :to => "pages#home"
  match "/signed_up" => "pages#signed_up", :as => "signed_up"
  match "/waiting_for_confirmation" => "pages#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/download" => "users#download", :as => "download"
  match "/stats" => "pages#stats", :as => "stats"
  match "/roster" => "pages#roster", :as => "roster"
  
  #Comments
  #=======================#
  match "/add_comment" => "comments#create", :as => "add_comment"
  match "/update_comment" => "comments#update", :as => "update_comment"
  match "/destroy_comment" => "comments#destroy", :as => "destroy_comment"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_one :schedule, :dependent => :destroy
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :comments, :dependent => :destroy
  
  # Alias for <tt>acts_as_taggable_on :tags</tt>: <tt>acts_as_taggable</tt>  
  acts_as_taggable_on :interests
  
  # Implementing acts_as_commentable_with_threading
  acts_as_commentable
  
  # mount_uploader :profile_image, ProfileImageUploader
  
  attr_accessible :name, :description, :invited_users, :max_members, :total_members, :privacy, :creator, :interest_list,
                  :profile_image, :discussion_section_1, :discussion_section_2, :discussion_section_3
                  
  # validates_presence_of :profile_image, :interest_list, :name, :description, :privacy, :creator
  validates_length_of :name, :within => 2..75, :too_long => "must be at most 75 characters", :too_short => "must be at least 2 characters"
  # validates_length_of :description, :within => 2..1500, :too_long => "must be at most 1500 characters", :too_short => "must be at least 2 characters"
  # validates_size_of :profile_image, :maximum => 5.megabytes
  
  
  #############################
  ###  Attribute Functions  ###
  #############################
  
  # Returns how large groups can get
  def self.max_group_size
    8
  end
  
  # Returns how small groups can be
  def self.min_group_size
    7
  end
  
  
  ###################################
  ###  Admin Interface Functions  ###
  ###################################
  
  # Returns an array of strings for all users, where each string contains a user's
  # grouping information
  def self.export
    groups = Group.all
    days = %w(Monday Tuesday Wednesday Thursday Friday Saturday Sunday)
    blocks = %w(morning afternoon evening)
    export_users = []
    # export_users << "Name,Email,,M,,,T,,,W,,,Th,,,F,,,S,,,Su,,Preferred Friends"
    # export_users << ",,am,noon,pm,am,noon,pm,am,noon,pm,am,noon,pm,am,noon,pm,am,noon,pm,am,noon,pm,"
    groups.each do |group|
        group.users.each do |user|
        user_days = []
        user_line = []
        7.times { user_days << ["","",""] }
        user_line << user.memberships.first.compatibility_score  #to get compatibility score? hopefully :( alvin
	user_line << user.last_name
        user_line << user.first_name
        user_line << user.email
        user_line << group.name
        if user.schedule
          user.schedule.days.each do |day|
            if day
              day.time_blocks.each do |block|
                user_days[days.index(day.name)][blocks.index(block.chunk_of_time)] = "Y"
              end
            end
          end
          user_days.each do |u_day|
            u_day.each do |u_block|
              user_line << u_block
            end
          end
          # user_line << user.parse_preferred_teammates
          user_line << user.preferred_teammates
          user_line << user.discussion_section_1
          user_line << user.discussion_section_2
          user_line << user.discussion_section_3
        end
        export_users << user_line
      end
      export_users << nil
    end
    
    export_users
  end
  
  
  ######################################
  ###  Grouping Algorithm Functions  ###
  ######################################
  
  # Priority for grouping users:
  #   1. Compatibility
  #   2. Friends
  #   3. Schedule
  # 
  # Compatibility:
  #   User has 1+ meeting times (discussion_section_x's) in common with group
  def self.group_users
    puts "Cleaning up..."
    clean_up_groups
    puts "Group by friends..."
    group_by_friends
    puts "Group by time blocks..."
    group_by_time_blocks
    puts "taking care of leftovers.."
    group_ungrouped_users

  end
  
  ###  Clean Up Groups Functions  ###
  
  # Destroys all groups and memberships
  def self.clean_up_groups
    memberships = Membership.all
    groups = Group.all
    
    memberships.each do |membership|
      membership.destroy
    end
    
    groups.each do |group|
      group.destroy
    end
  end
  
  
  ###  Group By Friends Functions  ###
  
  # Creates groups and throws users with preferred teammates into them
  # 
  # User is grouped with all preferred teammates with two constraints:
  #   1. Preferred teammates are all compatible
  #   2. All preferred teammates can fit into the group given Group.max_group_size
  # 
  # Compatibility:
  #   User has 1+ meeting times (discussion_section_x's) in common with group
  def self.group_by_friends
    users_with_preferred_teammates = []
    users = User.all
    
    # construct a list of users with preferred taemmates
    users.each do |user|
      users_with_preferred_teammates << user.email if !user.preferred_teammates.blank?
    end
    
    # find a group for each user and his preferred_teammates
    # do this until all users with preferred teammates are grouped
    while !users_with_preferred_teammates.empty?
      user = User.where(:email => users_with_preferred_teammates.first).first  # ha!
      # user.parse_preferred_teammates
      find_group_for(user)
      group = user.groups.first
      users_with_preferred_teammates.delete(user.email)
      preferred_teammates = user.preferred_available_teammates
      preferred_teammates.each do |teammate|
        preferred_teammate = User.where(:email => teammate).first
        
        # preferred teammates can only join if they have a compatible meeting time with the group
        if preferred_teammate and group.has_compatible_meeting_time_with(preferred_teammate) and preferred_teammate.groups.empty? and group.users.count < Group.max_group_size
          group.add_user(preferred_teammate, "friend")
        end
        
        # teammate should be deleted from lists regardless of if grouped or not
        # for sake of avoiding an infinite loop
        # ungrouped users will be dealt with later
        users_with_preferred_teammates.delete(teammate)
      end
    end
  end
  
  # Fits user into an existing group
  # Group must have space for user and all user's preferred teammates
  # User must be compatible with group
  # 
  # Compatibility:
  #   User has 1+ meeting times (discussion_section_x's) in common with group
  def self.find_group_for(user)
    groups = Group.all
    
    # if there are no groups, create one
    if groups.empty?
      group = Group.new(:name => "group_1", :creator => user.id)
      group.save
      group.add_user(user, "creator")
    # else fit the user and his preferred teammates into an existing group
    else
      groups.each do |group|
        # if group is not full
        if group.users.count < Group.max_group_size
          available_spots = Group.max_group_size - group.users.count
          spots_required = user.preferred_available_teammates.count + 1
          # if group has enough spots for current user and all his preferred teammates
          if available_spots >= spots_required
            # if at least 1 of user's monday availabilities mach up with the group's
            if user.groups.empty? and group.has_compatible_meeting_time_with(user)
              group.add_user(user, "meeting")
            end
          end
        end
      end
    end
    
    # if the user and his preferred teammates couldn't be fit into an existing 
    # group, create a new one
    if user.groups.empty?
	puts "creating group" + String(Group.all.length) +" out of " + String(User.all.length/8)
      create_and_join_group(user)
    end
  end
  
  # Creates a new group with user as creator
  # Adds user to group
  def self.create_and_join_group(user)
    group = Group.create(:name => "group_#{Group.all.count + 1}", :creator => user.id)
    group.add_user(user, "creator")
  end
  
  # Determines a compatibility score between user and group, then creates membership
  # Membership also stores the compatibility score
  # 
  # Compatibility score is in respect to group leader's schedule (as opposed to group's
  # schedule) as to not shaft members that join later
  def add_user(user, reason)
    compatibility_score = 0
    group_leader = User.find(self.creator)
    
    # initializing <tt>group</tt> because of something funky going on with <tt>self</tt> in this context
    group = Group.where(:creator => self.creator).first
    
    case reason
    when "creator"
      compatibility_score += 42
      self.initialize_group_meeting_times(user)
      self.initialize_group_schedule(user.schedule)  # leader must have a schedule..
    when "friend"
      compatibility_score += 21
      compatibility_score += user.number_of_compatible_time_blocks_with(group_leader.schedule)
    else
      compatibility_score += user.number_of_compatible_time_blocks_with(group_leader.schedule)
    end
    
    if reason != "creator"
      group.update_group_meeting_times(user)
      group.update_group_schedule(user.schedule) if user.schedule != nil
    end
    
    Membership.create(:group_id => self.id, :user_id => user.id, :compatibility_score => compatibility_score)
  end
  
  # Group meeting times = intersection of all user's meeting preferences
  # Really we only care about 0's (aka, the meeting time is not an option)
  def update_group_meeting_times(user)
    if self.discussion_section_1 > user.discussion_section_1
      self.discussion_section_1 = user.discussion_section_1
      self.save
    end
    if self.discussion_section_2 > user.discussion_section_2
      # logger.debug "kMEMBER discussion_section_2: #{user.email} #{user.discussion_section_2} | #{self.discussion_section_2}"
      self.discussion_section_2 = user.discussion_section_2
      self.save
    end
    if self.discussion_section_3 > user.discussion_section_3
      self.discussion_section_3 = user.discussion_section_3
      self.save
    end
  end
  
  # Group schedule = intersection of group schedule and <tt>schedule</tt>
  def update_group_schedule(schedule)
    self_days = self.schedule.days
    schedule_days = schedule.days
    

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @comment = Comment.new
    @root_comments = @group.root_comments
    @all_comments = @group.comment_threads
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    @group.creator = current_user.id
    @group.total_members = 1
    if @group.save
      @membership = Membership.new(:group_id => @group.id, :user_id => current_user.id)
      if @membership.save
        redirect_to @group, :notice => "Successfully created group."
      else
        flash[:error] = "We were not able to create your membership with this group, please try again :/"
        render :action => 'new'
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group, :notice  => "Successfully updated group."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url, :notice => "Successfully destroyed group."
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_comment.html.erb
<div id="comment_<%= comment.id %>" class="comments">
	
	<div class="comment">

		<div id="group_info">
			<div id="profile_image" class="floatLeft">
				<%= image_tag(comment.user.profile_image_url(:tiny)) %>
			</div>
			<div id="user_name" class="floatLeft"><%= link_to comment.user.first_name, comment.user %> <span class="time"> at <% if (Time.now() - 1.day) > comment.created_at %>
	              <%= comment.created_at.strftime("%D %r") %>
	           <% else %>
	               <%= comment.created_at.strftime("%r") %>
	           <% end %></span>
			</div>
			
			<div class="clear"></div>
		</div>
		<div class="comment_body"><%= comment.body %></div>
		
		<% if comment.is_root? %>
			<%= link_to "Reply", "javascript:void(0)", :class => "comment_link" %>
		<% end %>
		
		<div class="edit_comment">
			<%= form_for(comment, :url => update_comment_path) do |f| %>
			  <%= f.error_messages %>
			  <%= hidden_field_tag :comment_id, comment.id %>
			  <%= hidden_field_tag :group_id, @group.id %>
			  <p><%= f.text_area :body, :rows => 4 %></p>
			  <p><%= f.submit %></p>
			<% end %>
		</div>
	
		<div class="comment_form">
			<%= form_for(@comment, :url => add_comment_path) do |f| %>
			  <%= f.error_messages %>
			  <%= hidden_field_tag :parent_id, comment.id %>
			  <%= hidden_field_tag :group_id, @group.id %>
			  <p><%= f.text_area :body, :rows => 4 %></p>
			  <p><%= f.submit %></p>
			<% end %>
		</div>
	</div>

	<% if comment.has_children? %>
		<%= indented_render 1, :partial => 'groups/comment', :collection => comment.children %>
	<% end %>

</div>

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
	<%= image_tag(@group.profile_image_url(:thumb)) if @group.profile_image? %><br />
	<%= f.label :profile_image, "Add a picture for the Group: " %>
	<%= f.file_field :profile_image %>
	<%= f.hidden_field :profile_image_cache %><br /><br />
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
	<%= f.label :interest_list, "Add interests: " %><br />
  	<%= f.text_field :interest_list %>
  </p>
  <p>
    <%= f.label :invited_users %><br />
    <%= f.text_area :invited_users %>
  </p>
  <p>
    <%= f.label :max_members %><br />
    <%= f.text_field :max_members %>
  </p>
  <p>
    <%= f.label :privacy %><br />
    <%= f.text_field :privacy %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/groups/comment.html.erb
<%= form_for [@group, @comment] do |f| %>
  <%= f.error_messages %>
  <%= hidden_field_tag :parent_id, params[:parent_id] %>
  <p>
     <%= f.label :body %><br />
     <%= f.text_area :body %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/groups/edit.html.erb
<% title "Edit Group" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @group %> |
  <%= link_to "View All", groups_path %>
</p>

app/views/groups/index.html.erb
<% title "Groups" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Invited Users</th>
    <th>Max Members</th>
    <th>Total Members</th>
    <th>Privacy</th>
  </tr>
  <% for group in @groups %>
    <tr>
      <td><%= group.name %></td>
      <td><%= group.description %></td>
      <td><%= group.invited_users %></td>
      <td><%= group.max_members %></td>
      <td><%= group.total_members %></td>
      <td><%= group.privacy %></td>
      <td><%= link_to "Show", group %></td>
      <td><%= link_to "Edit", edit_group_path(group) %></td>
      <td><%= link_to "Destroy", group, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Group", new_group_path %></p>

app/views/groups/new.html.erb
<% title "New Group" %>

<%= render 'form' %>

<p><%= link_to "Back to List", groups_path %></p>

app/views/groups/show.html.erb
<% title "#{@group.name}" %>

<p><%= image_tag(@group.profile_image_url(:thumb)) %></p>

<p><%= link_to "Members", users_path(:group_id => @group) %></p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>
<p>
  <strong>Invited Users:</strong>
  <%= @group.invited_users %>
</p>
<p>
  <strong>Max Members:</strong>
  <%= @group.max_members %>
</p>
<p>
  <strong>Total Members:</strong>
  <%= @group.total_members %>
</p>
<p>
  <strong>Privacy:</strong>
  <%= @group.privacy %>
</p>

<p>
	<a href="javascript:void(0)" class="comment_link main_reply">Comment</a>
</p>

<div id="comment_form_0" class="comment_form_main">
	<%= form_for(@comment, :url => add_comment_path) do |f| %>
	  <%= f.error_messages %>
	  <%= hidden_field_tag :parent_id, nil %>
	  <%= hidden_field_tag :group_id, @group.id %>
	  <p><%= f.text_area :body, :rows => 4 %></p>
	  <p><%= f.submit %></p>
	<% end %>
</div>

<p></p>
<p>
	<div id="comments">
  		<%= render :partial => 'groups/comment', :collection => @root_comments %>
	</div>
</p>

<p>
  <% if current_user.id == @group.creator %>
  	<%= link_to "Edit", edit_group_path(@group) %> |
  	<%= link_to "Destroy", @group, :confirm => 'Are you sure?', :method => :delete %> |
	<%= link_to "View All", groups_path %>
  <% else %>
	<%= link_to "View All", groups_path %>
  <% end %>
</p>