config/routes.rb
Grooopme::Application.routes.draw do
  resources :time_blocks, :days, :schedules, :groups, :memberships

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "signup_wizard", :to => "registrations#signup_wizard"
  end
  
  resources :users, :only => [:index, :show]

  root :to => "pages#home"
  match "/signed_up" => "pages#signed_up", :as => "signed_up"
  match "/waiting_for_confirmation" => "pages#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/download" => "users#download", :as => "download"
  match "/stats" => "pages#stats", :as => "stats"
  match "/roster" => "pages#roster", :as => "roster"
  
  #Comments
  #=======================#
  match "/add_comment" => "comments#create", :as => "add_comment"
  match "/update_comment" => "comments#update", :as => "update_comment"
  match "/destroy_comment" => "comments#destroy", :as => "destroy_comment"
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :days, :dependent => :destroy
  belongs_to :user
  belongs_to :group
  
  attr_accessible :name, :description, :user_id, :group_id
  
  def time_blocks_count
    time_blocks_count = 0
    
    self.days.each do |day|
      day.time_blocks.count.times { time_blocks_count += 1 }
    end
    
    time_blocks_count
  end
  
  def self.export_object
    users = User.all
    days = %w(Monday Tuesday Wednesday Thursday Friday Saturday Sunday)
    blocks = %w(morning afternoon evening)
    schedule = [["0:0:","0:1:","0:2:"], ["1:0:","1:1:","1:2:"], ["2:0:","2:1:","2:2:"], ["3:0:","3:1:","3:2:"], ["4:0:","4:1:","4:2:"], ["5:0:","5:1:","5:2:"], ["6:0:","6:1:","6:2:"]]
    schedule_to_be_exported = []
    
    users.each do |user|
      if user.schedule
        user.schedule.days.each do |day|
          day.time_blocks.each do |block|
            schedule[days.index(day.name)][blocks.index(block.chunk_of_time)] += "#{user.email},"
          end
        end
      end
    end
    
    schedule.each do |block|
      block.each do |mini|
        schedule_to_be_exported << mini[0..(mini.size-2)]
      end
    end
    
    schedule_to_be_exported
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @schedules = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params[:schedule])
    if @schedule.save
      redirect_to @schedule, :notice => "Successfully created schedule."
    else
      render :action => 'new'
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update_attributes(params[:schedule])
      redirect_to @schedule, :notice  => "Successfully updated schedule."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedules_url, :notice => "Successfully destroyed schedule."
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for @schedule do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/schedules/edit.html.erb
<% title "Edit Schedule" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @schedule %> |
  <%= link_to "View All", schedules_path %>
</p>

app/views/schedules/index.html.erb
<% title "Schedules" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
  </tr>
  <% for schedule in @schedules %>
    <tr>
      <td><%= schedule.name %></td>
      <td><%= schedule.description %></td>
      <td><%= schedule.user_id %></td>
      <td><%= link_to "Show", schedule %></td>
      <td><%= link_to "Edit", edit_schedule_path(schedule) %></td>
      <td><%= link_to "Destroy", schedule, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Schedule", new_schedule_path %></p>

app/views/schedules/new.html.erb
<% title "New Schedule" %>

<%= render 'form' %>

<p><%= link_to "Back to List", schedules_path %></p>

app/views/schedules/show.html.erb
<% title "Schedule" %>

<p>
  <strong>Name:</strong>
  <%= @schedule.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @schedule.description %>
</p>
<p>
  <strong>User:</strong>
  <%= @schedule.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_schedule_path(@schedule) %> |
  <%= link_to "Destroy", @schedule, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", schedules_path %>
</p>