config/routes.rb
Grooopme::Application.routes.draw do
  resources :time_blocks, :days, :schedules, :groups, :memberships

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "signup_wizard", :to => "registrations#signup_wizard"
  end
  
  resources :users, :only => [:index, :show]

  root :to => "pages#home"
  match "/signed_up" => "pages#signed_up", :as => "signed_up"
  match "/waiting_for_confirmation" => "pages#waiting_for_confirmation", :as => "waiting_for_confirmation"
  match "/download" => "users#download", :as => "download"
  match "/stats" => "pages#stats", :as => "stats"
  match "/roster" => "pages#roster", :as => "roster"
  
  #Comments
  #=======================#
  match "/add_comment" => "comments#create", :as => "add_comment"
  match "/update_comment" => "comments#update", :as => "update_comment"
  match "/destroy_comment" => "comments#destroy", :as => "destroy_comment"
end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :time_blocks, :dependent => :destroy
  belongs_to :schedule
  
  attr_accessible :name, :date, :description, :schedule_id
  
  # Does a Day exist with this date?
  def self.exists?(date, schedule_id)
    day = Day.where(:date => date, :schedule_id => schedule_id)
    !day.empty?
  end
  
  # Does a Day exist with this name?
  def self.exists?(name, schedule_id)
    day = Day.where(:name => name, :schedule_id => schedule_id)
    !day.empty?
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  load_and_authorize_resource
  
  def index
    @days = Day.all
  end

  def show
    @day = Day.find(params[:id])
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.new(params[:day])
    if @day.save
      redirect_to @day, :notice => "Successfully created day."
    else
      render :action => 'new'
    end
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    @day = Day.find(params[:id])
    if @day.update_attributes(params[:day])
      redirect_to @day, :notice  => "Successfully updated day."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @day = Day.find(params[:id])
    @day.destroy
    redirect_to days_url, :notice => "Successfully destroyed day."
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for @day do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :schedule_id %><br />
    <%= f.text_field :schedule_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/days/edit.html.erb
<% title "Edit Day" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @day %> |
  <%= link_to "View All", days_path %>
</p>

app/views/days/index.html.erb
<% title "Days" %>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Description</th>
    <th>Schedule</th>
  </tr>
  <% for day in @days %>
    <tr>
      <td><%= day.name %></td>
      <td><%= day.date %></td>
      <td><%= day.description %></td>
      <td><%= day.schedule_id %></td>
      <td><%= link_to "Show", day %></td>
      <td><%= link_to "Edit", edit_day_path(day) %></td>
      <td><%= link_to "Destroy", day, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Day", new_day_path %></p>

app/views/days/new.html.erb
<% title "New Day" %>

<%= render 'form' %>

<p><%= link_to "Back to List", days_path %></p>

app/views/days/show.html.erb
<% title "Day" %>

<p>
  <strong>Name:</strong>
  <%= @day.name %>
</p>
<p>
  <strong>Date:</strong>
  <%= @day.date %>
</p>
<p>
  <strong>Description:</strong>
  <%= @day.description %>
</p>
<p>
  <strong>Schedule:</strong>
  <%= @day.schedule_id %>
</p>

<p>
  <%= link_to "Edit", edit_day_path(@day) %> |
  <%= link_to "Destroy", @day, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", days_path %>
</p>